### ISSUE TITLE
How to rebind keys with wakib?

### ISSUE THREAD

**Issue by sinekonata** [darkstego/wakib.d#4]
You've advised not to change the `init.el` file so that future updates wouldn't be overwriting our personal configs. So I've used `user-init.el` instead.
My issue is with rebinding keys. It seems not to work.
`(global-set-key (kbd "<f12>") 'wakib-keys)` For instance works because wakib doesn't use F12
`(global-set-key (kbd "M-3") 'digit-argument)` Only works if I deactivate `wakib-keys`

And for instance, in standard emacs `quoted-insert` to escape `<RET>` in search for instance is bound to C-q. So to use it as I had originally used, and since I don't use C-q to quit ever, I wanted to get back to the original way. But since
`(global-set-key (kbd "C-q") 'quoted-insert)`
 Only works w/o (outside minor mode?) `wakib-keys` and
`(define-key key-translation-map (kbd "C-q") 'quoted-insert)`
Doesn't work with `quoted-insert`. So I had to workaround with
`(global-set-key (kbd "<f11>") 'quoted-insert)`
`(define-key key-translation-map (kbd "C-q") (kbd "<f11>"))`
This is very inelegant and problematic as well. And I have more keys to rebind.
So how do I change the key bindings easily without changing the `init.el` file directly? Why is `global-set-key` being overridden if it's global? 

Thank you again for this amazing package. It's a million times better than just the wakib-keys.el btw. I love the M-; M-: keys <3

**Comment by darkstego** [comment]
The way the keymaps work, minor-mode keymaps take precedence over global keymap (which is the last thing checked). The way wakib-keys is designed it adds a keymap to the `emulation-mode-map-alist`. There are a few reasons it is done this way. First, if you edit the global keymap for a new keybindings package, you cannot disable it as the old configuration is overwritten. This way you can just disable wakib-keys and the old keybindings are there. The second reason is if you make the keybindings on the global map then they can get overwritten by minor maps that you use. If they are bindings that define your basic movements, you might suddenly not be able to move when certain minor modes are active. So I give it a higher priority.

There are two ways to solve this:

1. If you are overwriting a key to do something totally different from the original, like your example, then just overwrite the key in `wakib-keys-overriding-map` so basically:
 `(define-key wakib-keys-overriding-map (kbd "C-q") 'quoted-insert)`
2. If you are remapping all keys that do one thing to do something else, then you can just use remaps and those can be placed global-map. Let us say you wanted to implement your own undo function then you just:
`(define-key (current-global-map) [remap undo] 'my-undo)`


EDIT: I initially said minor mode instead of emulation mode.

**Comment by darkstego** [comment]
Also, I never used quoted-insert before, and it does look useful. I might need to add it to wakib-keys

**Comment by sinekonata** [comment]
I haven't found a use case for the 2nd method so far but the 1st one works amazingly, thank you.

**Comment by darkstego** [comment]
Added these instructions to the README.

**Comment by gety9** [comment]
@darkstego 

could you tell why you prefer to rebind keys using define-key in :config section (of use-package) vs using :bind?
(that's the impression i got from init.el)

**Comment by darkstego** [comment]
If I remember my use-package correctly the :bind actually does two things, first part is equivalent to define-key but the second part is defer loading of the package, and triggers load on the action associated with those key presses. So in cases where I want the package to load on that keypress (like avy) I use :bind but sometimes I want to redefine a infrequently used keybinding but I want the package to load up before that so I remap then in the :config section.

**Comment by gety9** [comment]
@darkstego 

"but the second part is defer loading of the package"
-yup, that's correct

"but I want the package to load up before that so I remap then in the :config section."
-couldn't you use :init? If no could you explain why it wouldn't work?

**Comment by darkstego** [comment]
-couldn't you use :init? If no could you explain why it wouldn't work?

:init occurs before loading the package. Most of the bindings are done in that mode-map so I need to load the package first. So if you aren't changing global bindings then you need to use :config rather than :init
